# Generated by Django 4.0.5 on 2022-06-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128, verbose_name='Nom du client')),
                ('contact', models.CharField(max_length=128, verbose_name='Contact du client')),
                ('adresse', models.CharField(max_length=128, verbose_name='Adresse du client')),
                ('tel', models.CharField(max_length=128, verbose_name='Téléphone')),
            ],
        ),
        migrations.CreateModel(
            name='OneDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_facture', models.CharField(max_length=128, verbose_name='Numéro de Facture')),
                ('destinataire', models.CharField(max_length=128, verbose_name='Destinataire')),
                ('bon_de_livraison', models.CharField(max_length=128, verbose_name='Bon de Livraison')),
                ('nombre_de_colis', models.CharField(max_length=128, verbose_name='Nombre de Colis')),
                ('type_de_paiment', models.CharField(choices=[('chèque', 'chèque'), ('espéce', 'espéce'), ('compte', 'compte'), ('autre', 'autre')], max_length=128, verbose_name='Type de Paiment')),
                ('status', models.CharField(blank=True, choices=[('livré', 'livré'), ('en cours', 'en cours'), ('retourné', 'retourné')], default='en cours', max_length=128, verbose_name='status de la livraisons')),
                ('creer_le', models.DateTimeField(auto_now_add=True, verbose_name='Livraison créer le :')),
            ],
        ),
    ]
